### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by EthanBoiLol** [Psycrow101/io_scene_bfbb_anm#1]
hi, while some animations, like [E6FC7E93] spongebob_spatula_grab.anm works just fine, some other anm, like [B6E8522A] spongebob_idle08.anm, appears to bring up an error

Traceback (most recent call last):
  File "/home/ethanboi/.config/blender/3.4/scripts/addons/io_scene_bfbb_anm/__init__.py", line 54, in execute
    return import_bfbb_anm.load(context, **keywords)
  File "/home/ethanboi/.config/blender/3.4/scripts/addons/io_scene_bfbb_anm/import_bfbb_anm.py", line 84, in load
    act = create_action(arm_obj, anm, fps)
  File "/home/ethanboi/.config/blender/3.4/scripts/addons/io_scene_bfbb_anm/import_bfbb_anm.py", line 47, in create_action
    kf_id = off[bone_id]
IndexError: tuple index out of range

after this error, the first frame of the animation loads, but no keyframes for the rest of the animation exists

**Comment by Psycrow101** [comment]
Greetings. Can you send me the .dff and .anm files?

**Comment by Psycrow101** [comment]
Solved https://github.com/Psycrow101/io_scene_bfbb_anm/commit/5aa04613be7a6ed4913610a20913daeb8f247db0
